<div class='alert alert-warning'>

These interactive examples with JupyterLite are experimental and
may not always work as expected. The execution of cells containing import
statements can result in high bandwidth usage and may take a long time to
load. They may not be in sync with the latest PyWavelets release.

Shall you encounter any issues, please feel free to report them on the
[PyWavelets issue tracker](https://github.com/PyWavelets/pywt/issues).

</div>

In [ ]:
import numpy as np
import pywt
data = np.linspace(1, 4, 7)
data

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [ ]:
pywt.threshold(data, 2, 'soft')

array([ 0. ,  0. ,  0. ,  0.5,  1. ,  1.5,  2. ])

In [ ]:
pywt.threshold(data, 2, 'hard')

array([ 0. ,  0. ,  2. ,  2.5,  3. ,  3.5,  4. ])

In [ ]:
pywt.threshold(data, 2, 'garrote')

array([ 0.        ,  0.        ,  0.        ,  0.9       ,  1.66666667,
        2.35714286,  3.        ])

In [ ]:
pywt.threshold(data, 2, 'greater')

array([ 0. ,  0. ,  2. ,  2.5,  3. ,  3.5,  4. ])

In [ ]:
pywt.threshold(data, 2, 'less')

array([ 1. ,  1.5,  2. ,  0. ,  0. ,  0. ,  0. ])